service.name: usermanagementservice
---
spring:
  profiles: development

welcome.msg: Welcome To Development Environment

---
spring:
  profiles: qa

welcome.msg: Welcome To QA Environment

---
spring:
  profiles: preProd

welcome.msg: Welcome To PreProd Environment


---
spring:
  profiles: prod

welcome.msg: Welcome To Prod Environment
